# Generated by Django 5.0.7 on 2024-07-18 11:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(default=app.models.generate_verification_code, max_length=5, unique=True),
        ),
    ]
